design design_name (same as filename);
{
    device 
    {
        architecture architecture_name;
        device device_name;
        package package_name;
        speed "speed";
    }
    signal signal_name
    {
        property
        {
            TW_IS_CONST_SIG boolean true/false
        }
    
        signal-pins
            // drivers
            (cell_location, pin_name)
            // loads
            (cell_location, pin_name)
            route
            dest.src
        dest.src
        dest.src
        dest.src
        dest.src
    }
    signal signal_name
    {
        property
        {
            TW_IS_CONST_SIG boolean true/false
        }
    
        signal-pins
            // drivers
            (cell_location, pin_name)
            // loads
            (cell_location, pin_name)
            route
            dest.src
        dest.src
        dest.src
        dest.src
        dest.src
    }
}
